#ifndef ERROR
#error "You must define ERROR macro before include this file"
#endif

//errors
/*--------------------------- Other errors -------------------------------*/
ERROR(ERROR_HEAD = 0,                  "dummy")
ERROR(OUT_OF_MEMORY,                   "内存不足\n")
ERROR(GRAMMAR_FILE_WITHOUT_ANY_RULE,   "语法文件没有任何产生式\n")
ERROR(NOT_FIND_SPECIFIY_START_SYMBOL,  "没有发现指定的开始符号 %s 将以 %s 作为开始符号\n")
ERROR(START_SYMBOL_APPEAR_RULE_RIGHT,  "开始符号 %s 出现在产生式右边,将自动生成新的开始符号 %s\n")
ERROR(THIS_RULE_CANNOT_BE_REDUCED,     "这个产生式无法被规约: ")
ERROR(CANNOT_OPEN_FILE,                "无法打开此文件:%s\n")
ERROR(NONTERMINAL_IMPLICIT_RULE,       "警告: 非终结符 %s 没有定义显式的产生式,已创建隐式产生式: %s -> .\n")
/*--------------------------- Command errors -----------------------------*/
ERROR(VALID_COMMAND_OPT_ARE,           "正确参数输入形式为：\n")
ERROR(UNDEF_OPT,                       "命令行语法错误:未定义的选项\n")
ERROR(MISSING_FLAG_ON_SWITCH,          "命令定义处错误:此选项不是一个标识\n")
ERROR(MISSING_VALUE_ON_SWITCH,         "命令定义处错误:此选项不是一个变量\n")
ERROR(MISSING_FUNC_ON_SWITCH,          "命令定义处错误:此选项不是一个函数\n")
ERROR(ILLEGAL_CHAR_IN_INTEGER_ARG,     "命令行语法错误:整形参数中含有非法字符\n")
ERROR(ILLEGAL_CHAR_IN_DOUBLE_ARG,      "命令行语法错误:浮点参数中含有非法字符\n")
ERROR(MISSING_RPAREN,                  "命令行语法错误:缺少右括号\n")
ERROR(FAILURE_R_NOTE,                  "\n%*s^-- 这里\n")
ERROR(FAILURE_L_NOTE,                  "\n%*s这里 --^\n")
ERROR(FILE_NOT_EXIST,                  "文件%s不存在,或您没有读取权限\n")
ERROR(MISSING_GRAMMAR_FILE,            "请输入要分析的语法文件名字\n")
/*--------------------------- Lexer errors -----------------------------*/
ERROR(ILLEGAL_CHARACTER,               "%s:%d:%d: 非法字符: \\x%02x\n")
ERROR(CODE_STRING_NOT_TERMINAL,        "%s:%d:%d: 代码块在文件结束前失去结束符: '%c'\n")
ERROR(VALUE_STRING_NOT_TERMINAL,       "%s:%d:%d: 字符串值在文件结束前失去结束符: '%c'\n")
ERROR(TYPE_STRING_NOT_TERMINAL,        "%s:%d:%d: 类型块在文件结束前失去结束符: '%c'\n")
ERROR(MEASURE_FAILED,                  "度量出错,请检查缓冲区大小,下标索引为: %d\n")
/*--------------------------- Parse errors -----------------------------*/
ERROR(CANNOT_READING_FILE,             "无法读取此文件:%s\n")
ERROR(CANNOT_ALLOC_MEM_HOLD_FILE,      "无法申请足够内存来存放此文件:%s\n")
ERROR(CANNOT_READ_FILE_IN_ALL_BYTES,   "无法一次性全部读取文件%s大小为%d\n")
ERROR(MISSING_DEF_END,                 "丢失结束标记%%endif起始处位于行:%d:%d\n")
ERROR(NOT_DECL_OR_RULE,                "%s:%d:%d: 非声明符或产生式开头:\n%s\n")
ERROR(INVALID_DECL_KEYWORD,            "%s:%d:%d: 无效的关键字: %s\n")
ERROR(RESYNC_AFTER_ERR,                "%s:%d:%d: 在此处进行错误后重同步\n")
ERROR(MISSING_CODE_BLOCK,              "%s:%d:%d: %%%s 丢失代码块\n")
ERROR(MISSING_TYPE_BLOCK,              "%s:%d:%d: %%%s 丢失类型块\n")
ERROR(NEED_IDENTIFIER,                 "%s:%d:%d: 需要一个标识符:\n%s\n")
ERROR(NEED_TERMINAL_SYMBOL,            "%s:%d:%d: 需要一个终结符:\n%s\n")
ERROR(NEED_NONTERMINAL_SYMBOL,         "%s:%d:%d: 需要一个非终结符:\n%s\n")
ERROR(SYMBOL_ALREADY_HAS_A_PRECEDENCE, "%s:%d:%d: 符号: %s 已经被赋予了优先级\n")
ERROR(CANNOT_ASSIGN_A_PRECEDENCE,      "%s:%d:%d: 对符号的优先级赋值失败:\n%s\n")
ERROR(INVALID_FALLBACK_TOKEN,          "%s:%d:%d: 无效的回退符号:\n%s\n")
ERROR(INVALID_DESTRUCT_SYMBOL,         "%s:%d:%d: 无效的析构符号:\n%s\n")
ERROR(INVALID_TYPE_SYMBOL,             "%s:%d:%d: 无效的类型符号:\n%s\n")
ERROR(EXPECTED_ARROW_OR_LPAREN,        "%s:%d:%d: 期待输入的是 \"->\" 或 \"(\" :%s\n")
ERROR(ALIAS_CONFLICT,                  "%s:%d:%d: 别名冲突的警告:\n%s\n")
ERROR(INVALID_ALIAS,                   "%s:%d:%d: 不是一个有效的别名:\n%s\n")
ERROR(LOST_RPAREN,                     "%s:%d:%d: 丢失\")\":\n%s\n")
ERROR(LOST_ARROW,                      "%s:%d:%d: 丢失\"->\":\n%s\n")
ERROR(LOST_RBRACKET,                   "%s:%d:%d: 丢失\"]\":\n%s\n")  
ERROR(UNRECOGNIZED_INPUT,              "%s:%d:%d: 未被识别的输入:\n%s\n")
ERROR(MISSING_PREVIOUS_RULE,           "%s:%d:%d: 代码块丢失对应的产生式:\n%s\n")
ERROR(RULE_CODE_ALREADY_EXISTED,       "%s:%d:%d: 产生式代码已经存在:\n%s\n")
ERROR(ALREADY_HAS_A_PRECEDENCE_SYMBOL, "%s:%d:%d: 产生式早已被赋予了优先符:\n%s\n")
ERROR(PARSE_ERR_COUNT,                 "对语法文件 \"%s\" 进行分析时产生的错误计数为: %d\n")
/*--------------------------- Generate errors ----------------------------*/
ERROR(CANNOT_FIND_TEMPLATE_FILE,       "找不到分析器的驱动模板文件\n")
ERROR(CANNOT_OPEN_TEMPLATE_FILE,       "无法打开分析器的驱动模板文件: %s 请检查文件是否可读\n")
ERROR(UNRECORDED_SYMBOL_TYPE,          "%s:%d:%d: 符号类型未登记,需要指定符号类型:\n%.*s\n")
ERROR(UNRECORDED_ALIAS,                "%s:%d:%d: 未登记的别名:\n%.*s\n")
ERROR(MISSING_SYMBOL_TYPE,             "%s:%d:%d: 类型不明确,需要指定符号类型:\n%.*s\n")
/*--------------------------- Out put errors ----------------------------*/
ERROR(INVALID_TPL_OUT_NAME,            "模板文件 \"%s\" 指定的输出文件 \"%s\" 创建失败,已创建新的输出文件 \"%s\"\n")
ERROR(INVALID_TPL_INCLUDE_NAME,        "模板文件 \"%s\" 指定的包含文件 \"%s\" 创建失败,已创建新的包含文件 \"%s\"\n")
/*--------------------------- Other errors -------------------------------*/
ERROR(ID_OUT_RANGE_ERR,                "找不到此类型的错误\n")
ERROR(MESSAGE_FORMAT_ERR,              "错误消息格式出错,位于索引 %d\n")
ERROR(ERROR_TAIL,                      "dummy")

